<?php

/**
 * Class for reading and writing NZB files on the hard disk,
 * building folder paths to store the NZB files.
 */
class NZB
{
	/**
	 * Instance of class site.
	 *
	 * @var object
	 * @access private
	 */
	private $s;

	/**
	 * Site settings.
	 *
	 * @var object
	 * @access private
	 */
	private $site;

	/**
	 * Determines if the site setting table per group is enabled.
	 *
	 * @var int
	 * @access private
	 */
	private $tablePerGroup;

	/**
	 * Group ID when writing NZBs.
	 * @var int
	 */
	protected $groupID;

	/**
	 * Instance of class db.
	 * @var DB
	 */
	protected $db;

	/**
	 * Date when writing NZBs.
	 * @var string
	 */
	protected $writeDate;

	/**
	 * Default constructor.
	 *
	 * @access public
	 */
	public function __construct()
	{
		$this->s = new Sites();
		$this->site = $this->s->get();
		$this->tablePerGroup = (isset($this->site->tablepergroup)) ? (int)$this->site->tablepergroup : 0;
	}

	/**
	 * Initiate class vars when writing NZB's.
	 *
	 * @param DB $db
	 * @param string $date
	 * @param int $groupID
	 */
	public function initiateForWrite($db, $date, $groupID)
	{
		$this->db = $db;
		$this->writeDate = $date;
		$this->groupID = $groupID;
	}

	/**
	 * Clean up class vars when done writing NZB's.
	 */
	public function cleanForWrite()
	{
		$this->writeDate = null;
		$this->groupID = null;
	}

	/**
	 * Write an NZB to the hard drive for a single release.
	 *
	 * @param int    $relID   The ID of the release in the DB.
	 * @param string $relGuid The guid of the release.
	 * @param string $name    The name of the release.
	 * @param string $cTitle  The name of the category this release is in.
	 *
	 * @return bool Have we successfully written the NZB to the hard drive?
	 *
	 * @access public
	 */
	public function writeNZBforReleaseId($relID, $relGuid, $name, $cTitle)
	{
		// Set table names
		if ($this->tablePerGroup === 1) {
			if ($this->groupID == '') {
				exit("$this->groupID is missing, are you running grabnzbs_threaded.py\n");
			}
			$group['cname'] = 'collections_' .$this->groupID;
			$group['bname'] = 'binaries_' . $this->groupID;
			$group['pname'] = 'parts_' . $this->groupID;
		} else {
			$group['cname'] = 'collections';
			$group['bname'] = 'binaries';
			$group['pname'] = 'parts';
		}

		if ($relID == '' || $relGuid == '') {
			return false;
		}

		$path = $this->getNZBPath($relGuid, $this->site->nzbsplitlevel, true);
		$fp = gzopen($path, 'w5');
		if ($fp) {
			$nzb_guid = '';
			gzwrite($fp,
				"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE nzb PUBLIC \"-//newzBin//DTD NZB 1.1//EN\" " .
				"\"http://www.newzbin.com/DTD/nzb/nzb-1.1.dtd\">\n<!-- NZB Generated by: nZEDb " .
				$this->s->version() . ' ' . $this->writeDate .
				" -->\n<nzb xmlns=\"http://www.newzbin.com/DTD/2003/nzb\">\n<head>\n <meta type=\"category\">" .
				htmlspecialchars($cTitle, ENT_QUOTES, 'utf-8') .
				"</meta>\n <meta type=\"name\">" .
				htmlspecialchars($name, ENT_QUOTES, 'utf-8') .
				"</meta>\n</head>\n\n"
			);

			$result =
				$this->db->query(
					sprintf(
					'SELECT ' . $group['cname'] . '.*, ' . $group['cname']
					. '.date AS udate, groups.name AS groupname FROM '
					. $group['cname'] . ' INNER JOIN groups ON '
					. $group['cname'] . '.groupid = groups.id WHERE '
					. $group['cname'] . '.releaseid = %d', $relID
					)
				);

			foreach ($result as $binrow) {
				$unixdate = strtotime($binrow['udate']);
				$poster = htmlspecialchars($binrow['fromname'], ENT_QUOTES, 'utf-8');
				$result2 = $this->db->query(
					sprintf(
						'SELECT id, name, totalparts FROM '
						. $group['bname']
						. ' WHERE collectionid = %d ORDER BY name', $binrow['id']
					)
				);

				foreach ($result2 as $binrow2) {
					gzwrite($fp,
						'<file poster="' . $poster .
						'" date="' . $unixdate . '" subject="' .
						htmlspecialchars($binrow2['name'], ENT_QUOTES, 'utf-8') .
						' (1/' . $binrow2['totalparts'] .
						")\">\n <groups>\n  <group>" . $binrow['groupname'] .
						"</group>\n </groups>\n <segments>\n"
					);

					$resparts = $this->db->query(
						sprintf(
							'SELECT DISTINCT(messageid), size, partnumber FROM '
							. $group['pname']
							. ' WHERE binaryid = %d ORDER BY partnumber', $binrow2['id'])
					);

					foreach ($resparts as $partsrow) {
						if ($nzb_guid === '') {
							$nzb_guid = $partsrow['messageid'];
						}

						gzwrite($fp, '  <segment bytes="' . $partsrow['size']
							. '" number="' . $partsrow['partnumber'] . '">'
							. htmlspecialchars($partsrow['messageid'], ENT_QUOTES, 'utf-8')
							. "</segment>\n"
						);
					}
					gzwrite($fp, " </segments>\n</file>\n");
				}
			}
			gzwrite($fp, '</nzb>');
			gzclose($fp);

			if (is_file($path)) {
				if ($nzb_guid === '') {
					$this->db->queryExec(
						sprintf(
							'UPDATE releases SET nzbstatus = 1 WHERE id = %d'
							, $relID
						)
					);
				} else {
					$this->db->queryExec(
						sprintf(
							'UPDATE releases SET nzbstatus = 1, nzb_guid = %s WHERE id = %d',
							$this->db->escapestring(md5($nzb_guid)), $relID
						)
					);
				}

				// Chmod to fix issues some users have with file permissions.
				chmod($path, 0777);
				return true;
			} else {
				echo "ERROR: $path does not exist.\n";
			}
		}
		return false;
	}

	/**
	 * Compress an imported NZB and store it inside the nzbfiles folder.
	 *
	 * @param string $relguid    The guid of the release.
	 * @param string $nzb        String containing the imported NZB.
	 *
	 * @return bool
	 *
	 * @access public
	 *
	 */
	public function copyNZBforImport($relguid, $nzb)
	{
		$path = $this->getNZBPath($relguid, 0, true);
		$fp = gzopen($path, 'w5');
		if ($fp && $nzb) {
			$date1 = htmlspecialchars(date('F j, Y, g:i a O'), ENT_QUOTES, 'utf-8');
			$article =
				preg_replace(
					'/dtd">\s*<nzb xmlns=/', "dtd\">\n<!-- NZB Generated by: nZEDb "
					. $this->s->version() . ' ' . $date1 . " -->\n<nzb xmlns=", $nzb
				);

			gzwrite($fp,
				preg_replace(
					'/<\/file>\s*(<!--.+)?\s*<\/nzb>\s*/si'
					, "</file>\n  <!--GrabNZBs-->\n</nzb>"
					, $article
				)
			);

			gzclose($fp);
			// Chmod to fix issues some users have with file permissions.
			chmod($path, 0777);
			return true;
		} else {
			echo "ERROR: NZB already exists?\n";
			return false;
		}
	}

	/**
	 * Build a folder path on the hard drive where the NZB file will be stored.
	 *
	 * @param string $releaseGuid         The guid of the release.
	 * @param int    $levelsToSplit       How many sub-paths the folder will be in.
	 * @param bool   $createIfDoesntExist Create the folder if it doesn't exist.
	 *
	 * @return string $nzbpath The path to store the NZB file.
	 *
	 * @access public
	 */
	private function buildNZBPath($releaseGuid, $levelsToSplit, $createIfDoesntExist)
	{
		$sitenzbpath = $this->site->nzbpath;
		if (substr($sitenzbpath, strlen($sitenzbpath) - 1) !== DS) {
			$sitenzbpath = $sitenzbpath . DS;
		}

		$subpath = '';

		for ($i = 0; $i < $levelsToSplit; $i++) {
			$subpath = $subpath . substr($releaseGuid, $i, 1) . DS;
		}

		$nzbpath = $sitenzbpath . $subpath;

		if ($createIfDoesntExist && !is_dir($nzbpath)) {
			mkdir($nzbpath, 0777, true);
		}

		return $nzbpath;
	}

	/**
	 * Retrieve path + filename of the NZB to be stored.
	 *
	 * @param string $releaseGuid         The guid of the release.
	 * @param int    $levelsToSplit       How many sub-paths the folder will be in. (optional)
	 * @param bool   $createIfDoesntExist Create the folder if it doesn't exist. (optional)
	 *
	 * @return string Path+filename.
	 *
	 * @access public
	 */
	public function getNZBPath($releaseGuid, $levelsToSplit=0, $createIfDoesntExist = false)
	{
		if ($levelsToSplit === 0) {
			$levelsToSplit = $this->site->nzbsplitlevel;
		}

		$nzbpath = $this->buildNZBPath($releaseGuid, $levelsToSplit, $createIfDoesntExist);
		return $nzbpath . $releaseGuid . '.nzb.gz';
	}

	/**
	 * Determine is an NZB exists, returning the path+filename, if not return false.
	 *
	 * @param string $releaseGuid   The guid of the release.
	 * @param int    $levelsToSplit How many sub-paths the folder will be in. (optional)
	 *
	 * @return bool   If false.
	 * @return string Path+file name of the nzb.
	 *
	 * @access public
	 */
	public function NZBPath($releaseGuid, $levelsToSplit=0)
	{
		if ($levelsToSplit === 0) {
			$levelsToSplit = $this->site->nzbsplitlevel;
		}

		$nzbfile = $this->getNZBPath($releaseGuid, $levelsToSplit);
		return !is_file($nzbfile) ? false : $nzbfile;
	}

	/**
	 * Retrieve various information on a NZB file (the subject, # of pars,
	 * file extensions, file sizes, file completion, group names, # of parts).
	 *
	 * @param string $nzb The NZB contents in a string.
	 *
	 * @return array $result Empty if not an NZB or the contents of the NZB.
	 *
	 * @access public
	 */
	public function nzbFileList($nzb)
	{
		$num_pars = $i = 0;
		$result = array();

		$nzb = str_replace("\x0F", '', $nzb);
		$xml = @simplexml_load_string($nzb);
		if (!$xml || strtolower($xml->getName()) !== 'nzb') {
			return $result;
		}

		foreach ($xml->file as $file) {
			// Subject.
			$title = $file->attributes()->subject;

			// Amount of pars.
			if (preg_match('/\.par2/i', $title)) {
				$num_pars++;
			}

			$result[$i]['title'] = $title;

			// Extensions.
			if (preg_match(
					'/\.(\d{2,3}|7z|ace|ai7|srr|srt|sub|aiff|asc|avi|audio|bin|bz2|'
					. 'c|cfc|cfm|chm|class|conf|cpp|cs|css|csv|cue|deb|divx|doc|dot|'
					. 'eml|enc|exe|file|gif|gz|hlp|htm|html|image|iso|jar|java|jpeg|'
					. 'jpg|js|lua|m|m3u|mkv|mm|mov|mp3|mp4|mpg|nfo|nzb|odc|odf|odg|odi|odp|'
					. 'ods|odt|ogg|par2|parity|pdf|pgp|php|pl|png|ppt|ps|py|r\d{2,3}|'
					. 'ram|rar|rb|rm|rpm|rtf|sfv|sig|sql|srs|swf|sxc|sxd|sxi|sxw|tar|'
					. 'tex|tgz|txt|vcf|video|vsd|wav|wma|wmv|xls|xml|xpi|xvid|zip7|zip)'
					. '[" ](?!(\)|\-))/i', $file->attributes()->subject, $ext)) {

				if (preg_match('/\.r\d{2,3}/i', $ext[0])) {
					$ext[1] = 'rar';
				}

				$result[$i]['ext'] = strtolower($ext[1]);
			} else {
				$result[$i]['ext'] = '';
			}

			$filesize = $numsegs = 0;

			// File size.
			foreach ($file->segments->segment as $segment) {
				$filesize += $segment->attributes()->bytes;
				$numsegs++;
			}
			$result[$i]['size'] = $filesize;

			// File completion.
			if (preg_match('/(\d+)\)$/', $title, $parts)) {
				$result[$i]['partstotal'] = $parts[1];
			}
			$result[$i]['partsactual'] = $numsegs;

			// Groups.
			if (!isset($result[$i]['groups'])) {
				$result[$i]['groups'] = array();
			}
			foreach ($file->groups->group as $g) {
				array_push($result[$i]['groups'], (string) $g);
			}

			// Parts.
			if (!isset($result[$i]['segments'])) {
				$result[$i]['segments'] = array();
			}
			foreach ($file->segments->segment as $s) {
				array_push($result[$i]['segments'], (string) $s);
			}

			unset($result[$i]['segments']['@attributes']);
			$i++;
		}
		return $result;
	}

}
