//
UPDATE settings SET section = 'indexer', SET subsection = 'max', SET NAME = 'articles', WHERE setting = 'maxmssgs'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'add', WHERE setting = 'maxaddprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'anidb', WHERE setting = 'maxanidbprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'books', WHERE setting = 'maxbooksprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'games', WHERE setting = 'maxgamesprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'imdb', WHERE setting = 'maximdbprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'music', WHERE setting = 'maxmusicprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'nfo', WHERE setting = 'maxnfoprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'nzbs', WHERE setting = 'maxnzbsprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'partsretry', WHERE setting = 'maxpartsprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'rage', WHERE setting = 'maxrageprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_process', SET NAME = 'xxx', WHERE setting = 'maxxxxprocessed'
UPDATE settings SET section = 'indexer', SET subsection = 'max_repair', SET NAME = 'parts', WHERE setting = 'maxpartrepair'
UPDATE settings SET section = 'indexer', SET subsection = 'max_size', SET NAME = 'form_release', WHERE setting = 'maxsizetoformrelease'
UPDATE settings SET section = 'indexer', SET subsection = 'max_size', SET NAME = 'post_process', WHERE setting = 'maxsizetopostprocess'
