ALTER TABLE binaries MODIFY binaryhash CHAR(32) CHARACTER SET latin1 NOT NULL DEFAULT '0';

DROP PROCEDURE IF EXISTS tpg_change;

DELIMITER $$

CREATE PROCEDURE tpg_change() BEGIN DECLARE done INT DEFAULT false; DECLARE _table CHAR(255); DECLARE _stmt VARCHAR(1000); DECLARE cur1 CURSOR FOR SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = "nzedb" AND TABLE_NAME LIKE "binaries_%"; DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE; OPEN cur1; myloop: loop FETCH cur1 INTO _table; IF done THEN LEAVE myloop; END IF; SET @sql := CONCAT("ALTER TABLE ", _table," MODIFY binaryhash VARCHAR(32) CHARACTER SET latin1 NOT NULL DEFAULT '0'"); PREPARE _stmt FROM @sql; EXECUTE _stmt; DROP PREPARE _stmt; END loop; CLOSE cur1; END $$

DELIMITER ;

DROP PROCEDURE tpg_change;
