CREATE TABLE `binaryblacklist` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `groupname` VARCHAR(255) NULL,
  `regex` VARCHAR(2000) NOT NULL,
  `optype` INT(11) UNSIGNED NOT NULL DEFAULT 1,
  `status` INT(11) UNSIGNED NOT NULL DEFAULT 1,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MYISAM AUTO_INCREMENT=100000 ;