INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.dvdr', 'This group contains DVD Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.boneless', 'This group contains XVID and X264 Movies. Some Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia', 'This group contains TV, Movies, and Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.movies.divx', 'This group contains XVID Movies');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.games.xbox', 'This group contains original XBOX Games.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.movies.xvid', 'This group contains XVID Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sony.psp', 'This group contains PSP Games.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.nintendo.ds', 'This group contains Nintendo DS Games');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.games.nintendods', 'This group contains Nintendo DS Games ');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.hdtv.x264', 'This group contains X264 Movies and HDTV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.games.xbox360', 'This group contains XBOX 360 Games and DLC.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.games.wii', 'This group contains Nintendo WII Games, WII-Ware, and VC.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.wmvhd', 'This group contains WMVHD Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.x264', 'This group contains X264 Movies and TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.wii', 'This group contains Nintendo WII Games, WII-Ware, and VC.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.moovee', 'This group contains XVID and X264 Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.inner-sanctum', 'This group contains PC and Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.warez.smartphone', 'This group contains Mobile Phone Apps.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.teevee', 'This group contains X264 and XVID TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.warez', 'This group contains PC 0DAY, PC ISO, and PC PHONE.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.complete_cd', 'This group contains a variety of Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.mpeg.video.music', 'This group contains a variety of Music Videos.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.mp3', 'This group contains a variety of Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.mma', 'This group contains MMA/TNA Sport TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.classical', 'This group contains Classical Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.mac', 'This group contains MAC/OSX Software.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.e-book', 'This group contains E-Books.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.warez.ibm-pc.0-day', 'This group contains PC-0Day.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.tvseries', 'This group contains X264 and XVID TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.ath', 'This group contains a variety of Music. Some Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.ftn', 'This group contains a variety of Music and TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.erotica', 'This group contains XXX.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.games', 'This group contains PC and Console Games.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.cores', 'This group contains a variety including Nintendo DS. Lots of Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.country.mp3', 'This group contains Country Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.1990s', 'This group contains Music from the 1990\'s.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.console.ps3', 'This group contains PS3 Games.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.scary.exe.files', 'This group contains XVID and X264 Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.cd.image', 'This group contains PC-ISO.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.e-book.technical', 'This group contains E-Books.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.erotica.divx', 'This group contains XXX.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.test', 'This group contains a variety of content.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.x', 'This group contains a variety of content. Some Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.hou', 'This group contains a variety of content. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.pro-wrestling', 'This group contains WWE Sport TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.lossless', 'This group contains a variety of Lossless Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.comp', 'This group contains Warez. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.warez.quebec-hackers', 'This group contains PC-0day. Some Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.bluegrass', 'This group contains Bluegrass Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.radio.bbc', 'This group contains BBC Radio Music');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.e-book.flood', 'This group contains E-Books.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.movies.erotica', 'This group contains XXX');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.documentaries', 'This group contains Documentary Movies and TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.jazz', 'This group contains Jazz Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.erotica.amateur', 'This group contains XXX.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.1960s.mp3', 'This group contains Music from the 1960\'s.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.1970s.mp3', 'This group contains Music from the 1970\'s.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.comedy', 'This group contains Comedy Audio.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.2000s', 'This group contains Music from the 2000\'s.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.christian', 'This group contains Christian Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.1950s', 'This group contains Music from the 1950\'s.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.1970s', 'This group contains Music from the 1970\'s.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.1980s', 'This group contains Music from the 1980\'s.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.mp3.bootlegs', 'This group contains Bootleg Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3', 'This group contains a variety of Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.mp3.audiobooks', 'This group contains Audio Books.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.rap-hiphop.full-albums', 'This group contains Rap and Hip-Hop Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.full_albums', 'This group contains a variety of Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.teen-idols', 'This group contains Music from Teen Idols');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.dance', 'This group contains Dance Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.warez.uk.mp3', 'This group contains a variety of Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.heavy-metal', 'This group contains Heavy Metal Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.cartoons', 'This group contains Cartoon TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.sports', 'This group contains Sports TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.anime', 'This group contains Anime TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.lossless.classical', 'This group contains lossless Classical Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.disney', 'This group contains Disney TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.nospam', 'This group contains a variety of Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.sitcoms', 'This group contains Sitcom TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.radio.british', 'This group contains British Radio Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.comedy.british', 'This group contains British Comedy TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.etc', 'This group contains a variety of items.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.misc', 'This group contains a variety of items.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.rock', 'This group contains Rock Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.dc', 'This group contains XVID and X264 Movies and TV. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.documentaries', 'This group contains Documentaries TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.cd.lossless', 'This group contains a variety of lossless Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.audiobooks.repost', 'This group contains Audiobooks.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.highspeed', 'This group contains XVID Movies. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.bloaf', 'This group contains a variety. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.big', 'This group contains XVID Movies. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.musicals', 'This group contains Musicals Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sound.mp3', 'This group contains a variety of Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.jazz.vocals', 'This group contains Jazz Vocal Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.dvd.movies', 'This group contains DVDR Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.ebook', 'This group contains Ebook\'s.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.disco', 'This group contains Disco Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.mp3.full_albums', 'This group contains a variety of Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.tv', 'This group contains XVID TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.lossless.country', 'This group contains lossless Country Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.uzenet', 'This group contains XXX. Some Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.mom', 'This group contains a variety. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.ijsklontje', 'This group contains XXX.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.lossless.1960s', 'This group contains lossless 1960\'s Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.emo', 'This group contains Emo Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.classic.tv.shows', 'This group contains Classic TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.dgma', 'This group contains XVID Movies. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.opera', 'This group contains Opera Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.ipod.videos', 'This group contains Mobile TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.music.opera', 'This group contains Opera Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.flac.jazz', 'This group contains lossless Jazz Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.tv', 'This group contains XVID and X264 TV.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.whitburn.pop', 'This group contains Pop Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sound.audiobooks', 'This group contains Audiobooks.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.acoustic', 'This group contains Accoustic Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.u-4all', 'This group contains XVID TV and Movies. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.sounds.mp3.progressive-country', 'This group contains Country Music.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.multimedia.classic-films', 'This group contains Classic TV and Movies.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.music.flac', 'This group contains a variety of lossless Music');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.ghosts', 'This group contains XVID TV and Movies. Mostly Foreign.');
INSERT INTO `groups` (`name`, `description`) VALUES ('alt.binaries.town', 'This group contains XVID TV and Movies. Mostly Foreign.');
