ALTER TABLE releases ALTER nzbstatus DROP DEFAULT;
ALTER TABLE releases ALTER nzbstatus TYPE BIT USING (CASE WHEN nzbstatus THEN 1 ELSE 0 END)::bit;
ALTER TABLE releases ALTER nzbstatus SET DEFAULT 0::bit;
ALTER TABLE releases ALTER nzbstatus SET NOT NULL;
ALTER TABLE releases ALTER iscategorized DROP DEFAULT;
ALTER TABLE releases ALTER iscategorized TYPE BIT USING (CASE WHEN iscategorized THEN 1 ELSE 0 END)::bit;
ALTER TABLE releases ALTER iscategorized SET DEFAULT 0::bit;
ALTER TABLE releases ALTER iscategorized SET NOT NULL;
ALTER TABLE releases ALTER isrenamed DROP DEFAULT;
ALTER TABLE releases ALTER isrenamed TYPE BIT USING (CASE WHEN isrenamed THEN 1 ELSE 0 END)::bit;
ALTER TABLE releases ALTER isrenamed SET DEFAULT 0::bit;
ALTER TABLE releases ALTER isrenamed SET NOT NULL;
ALTER TABLE releases ALTER ishashed DROP DEFAULT;
ALTER TABLE releases ALTER ishashed TYPE BIT USING (CASE WHEN ishashed THEN 1 ELSE 0 END)::bit;
ALTER TABLE releases ALTER ishashed SET DEFAULT 0::bit;
ALTER TABLE releases ALTER ishashed SET NOT NULL;
ALTER TABLE releases ALTER isrequestid DROP DEFAULT;
ALTER TABLE releases ALTER isrequestid TYPE BIT USING (CASE WHEN isrequestid THEN 1 ELSE 0 END)::bit;
ALTER TABLE releases ALTER isrequestid SET DEFAULT 0::bit;
ALTER TABLE releases ALTER isrequestid SET NOT NULL;
ALTER TABLE releases ALTER jpgstatus DROP DEFAULT;
ALTER TABLE releases ALTER jpgstatus TYPE BIT USING (CASE WHEN jpgstatus=1 THEN 1 ELSE 0 END)::bit;
ALTER TABLE releases ALTER jpgstatus SET DEFAULT 0::bit;
ALTER TABLE releases ALTER jpgstatus SET NOT NULL;
ALTER TABLE releases ALTER videostatus DROP DEFAULT;
ALTER TABLE releases ALTER videostatus TYPE BIT USING (CASE WHEN videostatus=1 THEN 1 ELSE 0 END)::bit;
ALTER TABLE releases ALTER videostatus SET DEFAULT 0::bit;
ALTER TABLE releases ALTER videostatus SET NOT NULL;
ALTER TABLE releases ALTER audiostatus DROP DEFAULT;
ALTER TABLE releases ALTER audiostatus TYPE BIT USING (CASE WHEN audiostatus=1 THEN 1 ELSE 0 END)::bit;
ALTER TABLE releases ALTER audiostatus SET DEFAULT 0::bit;
ALTER TABLE releases ALTER audiostatus SET NOT NULL;
ALTER TABLE releases ADD COLUMN proc_pp BIT NOT NULL DEFAULT 0::bit;
ALTER TABLE releases ADD COLUMN proc_sorter BIT NOT NULL DEFAULT 0::bit;
ALTER TABLE releases ADD COLUMN proc_par2 BIT NOT NULL DEFAULT 0::bit;
ALTER TABLE releases ADD COLUMN proc_nfo BIT NOT NULL DEFAULT 0::bit;
ALTER TABLE releases ADD COLUMN proc_files BIT NOT NULL DEFAULT 0::bit;

UPDATE releases SET proc_pp = 1::bit WHERE (bitwise & 8) = 8;
UPDATE releases SET proc_sorter = 1::bit WHERE (bitwise & 16) = 16;
UPDATE releases SET proc_par2 = 1::bit WHERE (bitwise & 32) = 32;
UPDATE releases SET proc_nfo = 1::bit WHERE (bitwise & 64) = 64;
UPDATE releases SET proc_files = 1::bit WHERE (bitwise & 128) = 128;

ALTER TABLE releases DROP COLUMN bitwise;

UPDATE site SET value = '178' WHERE setting = 'sqlpatch';
